name = "gleaky"
version = "0.1.0"

description = "A gleam library for defining RDBMS table structure and build queries for those tables."
licences = ["Apache-2.0"]
repository = { type = "github", user = "andho", repo = "gleaky" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
birdie = ">= 1.2.6 and < 2.0.0"
cake = ">= 2.1.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
pprint = ">= 1.0.5 and < 2.0.0"
